-- =====================================================
-- ROBOTS TABLE SCHEMA
-- Main product catalog for all robot types
-- =====================================================

CREATE TABLE IF NOT EXISTS public.robots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Basic Information
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  
  -- Categorization
  type TEXT NOT NULL, -- Main category: 'Humanoid Robots', 'Drones', 'Security Gadgets', 'Essential AI Gadgets and Smart Homes'
  sub_category TEXT DEFAULT 'General', -- Usage: 'Rental', 'Education', 'Expos', 'Events', 'Agriculture', 'Security', 'General'
  
  -- Media
  image_url TEXT,
  
  -- Technical Specifications (Optional - can be NULL)
  height TEXT, -- e.g., '110 cm'
  weight TEXT, -- e.g., '30 kg'
  battery_life TEXT, -- e.g., '90 mins'
  speed TEXT, -- e.g., '1.6 m/s'
  payload_capacity TEXT, -- e.g., '23 kg'
  
  -- Pricing (Optional)
  rental_price_daily DECIMAL(10, 2),
  rental_price_weekly DECIMAL(10, 2),
  rental_price_monthly DECIMAL(10, 2),
  purchase_price DECIMAL(10, 2),
  
  -- Availability
  is_available BOOLEAN DEFAULT TRUE,
  stock_quantity INTEGER DEFAULT 1,
  
  -- Additional Details
  datasheet_url TEXT,
  video_url TEXT,
  features JSONB, -- Store array of features as JSON
  
  -- Metadata
  tags TEXT[], -- Array of searchable tags
  manufacturer TEXT,
  model_number TEXT,
  year_released INTEGER
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_robots_type ON public.robots(type);
CREATE INDEX IF NOT EXISTS idx_robots_sub_category ON public.robots(sub_category);
CREATE INDEX IF NOT EXISTS idx_robots_is_available ON public.robots(is_available);
CREATE INDEX IF NOT EXISTS idx_robots_tags ON public.robots USING GIN(tags);

-- Function to update 'updated_at' timestamp
CREATE OR REPLACE FUNCTION update_robots_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for auto-updating updated_at
DROP TRIGGER IF EXISTS trigger_update_robots_updated_at ON public.robots;
CREATE TRIGGER trigger_update_robots_updated_at
    BEFORE UPDATE ON public.robots
    FOR EACH ROW
    EXECUTE FUNCTION update_robots_updated_at();

-- Sample data
INSERT INTO public.robots (name, type, sub_category, description, image_url, height, weight, battery_life, speed) 
VALUES 
  ('Humanoid Alpha', 'Humanoid Robots', 'Rental', 'Advanced bipedal robot for multi-purpose applications', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', '110 cm', '30 kg', '90 mins', '1.6 m/s'),
  ('Humanoid Beta', 'Humanoid Robots', 'Education', 'Educational humanoid robot for STEM programs', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', '105 cm', '28 kg', '120 mins', '1.4 m/s'),
  ('Drone X-1', 'Drones', 'Agriculture', 'High-performance aerial vehicle for crop monitoring', 'https://images.unsplash.com/photo-1506947411487-a56738267384?auto=format&fit=crop&w=800&q=80', NULL, '2.5 kg', '45 mins', '15 m/s'),
  ('SmartEye Cam', 'Security Gadgets', 'Security', 'AI-powered security camera with real-time threat detection', 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80', '15 cm', '0.5 kg', 'AC Powered', NULL),
  ('Butler AI', 'Essential AI Gadgets and Smart Homes', 'General', 'Integrated AI solution for smart home automation', 'https://images.unsplash.com/photo-1558002038-1091a1661116?auto=format&fit=crop&w=800&q=80', '30 cm', '1.2 kg', 'AC Powered', NULL)
ON CONFLICT DO NOTHING;

-- Enable Row Level Security (for Supabase)
ALTER TABLE public.robots ENABLE ROW LEVEL SECURITY;

-- Public read access policy
CREATE POLICY "Allow public read access on robots" ON public.robots
  FOR SELECT USING (true);

-- Admin write access policy (requires authentication)
CREATE POLICY "Allow admin write access on robots" ON public.robots
  FOR ALL USING (auth.role() = 'authenticated');
