-- =====================================================
-- CONTACTS TABLE SCHEMA
-- Stores contact form submissions from website
-- =====================================================

CREATE TABLE IF NOT EXISTS public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Contact Information
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  
  -- Organization
  company TEXT NOT NULL,
  industry TEXT NOT NULL,
  
  -- Message
  message TEXT NOT NULL,
  
  -- Status tracking (for CRM)
  status TEXT DEFAULT 'new', -- 'new', 'contacted', 'qualified', 'closed'
  assigned_to TEXT,
  notes TEXT,
  
  -- Metadata
  source TEXT DEFAULT 'website', -- 'website', 'phone', 'email', 'event'
  ip_address TEXT,
  user_agent TEXT
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_contacts_email ON public.contacts(email);
CREATE INDEX IF NOT EXISTS idx_contacts_status ON public.contacts(status);
CREATE INDEX IF NOT EXISTS idx_contacts_created_at ON public.contacts(created_at DESC);

-- Enable Row Level Security (for Supabase)
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- Public insert access policy (anyone can submit contact form)
CREATE POLICY "Allow public insert on contacts" ON public.contacts
  FOR INSERT WITH CHECK (true);

-- Admin read access policy (only authenticated users can read)
CREATE POLICY "Allow admin read access on contacts" ON public.contacts
  FOR SELECT USING (auth.role() = 'authenticated');

-- Admin update access policy
CREATE POLICY "Allow admin update access on contacts" ON public.contacts
  FOR UPDATE USING (auth.role() = 'authenticated');
