-- =====================================================
-- ADMINS TABLE SCHEMA
-- Stores admin user credentials and permissions
-- =====================================================

CREATE TABLE IF NOT EXISTS public.admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Authentication
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL, -- Hashed with bcrypt
  
  -- Profile
  full_name TEXT,
  role TEXT DEFAULT 'admin', -- 'admin', 'super_admin', 'viewer'
  
  -- Status
  is_active BOOLEAN DEFAULT TRUE,
  last_login TIMESTAMPTZ,
  
  -- Security
  failed_login_attempts INTEGER DEFAULT 0,
  locked_until TIMESTAMPTZ
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_admins_email ON public.admins(email);
CREATE INDEX IF NOT EXISTS idx_admins_is_active ON public.admins(is_active);

-- Function to update 'updated_at' timestamp
CREATE OR REPLACE FUNCTION update_admins_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for auto-updating updated_at
DROP TRIGGER IF EXISTS trigger_update_admins_updated_at ON public.admins;
CREATE TRIGGER trigger_update_admins_updated_at
    BEFORE UPDATE ON public.admins
    FOR EACH ROW
    EXECUTE FUNCTION update_admins_updated_at();

-- Insert default admin user
-- Email: robotbeings@gmail.com
-- Password: MailBala&*^001 (hashed)
INSERT INTO public.admins (email, password, full_name, role) 
VALUES ('robotbeings@gmail.com', '$2b$10$kWbaQhpY1MtndXuICGB5Zuw..wBCMtSc233fs4QS0kM8netYyBPL6', 'Admin User', 'super_admin')
ON CONFLICT (email) DO NOTHING;

-- Enable Row Level Security (for Supabase)
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

-- Only authenticated admins can read admin table
CREATE POLICY "Allow admin read access on admins" ON public.admins
  FOR SELECT USING (auth.role() = 'authenticated');

-- Only super_admins can modify admin table
CREATE POLICY "Allow super_admin write access on admins" ON public.admins
  FOR ALL USING (auth.jwt() ->> 'role' = 'super_admin');
