-- =====================================================
-- RENTAL BOOKINGS TABLE SCHEMA (OPTIONAL - FUTURE USE)
-- Stores rental booking information and tracking
-- =====================================================

CREATE TABLE IF NOT EXISTS public.rental_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Robot Reference
  robot_id BIGINT REFERENCES public.robots(id) ON DELETE CASCADE,
  
  -- Customer Information
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_company TEXT,
  customer_address TEXT,
  
  -- Booking Details
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  duration_days INTEGER NOT NULL,
  
  -- Pricing
  total_price DECIMAL(10, 2) NOT NULL,
  deposit_amount DECIMAL(10, 2),
  discount_amount DECIMAL(10, 2) DEFAULT 0,
  
  -- Status
  status TEXT DEFAULT 'pending', -- 'pending', 'confirmed', 'active', 'completed', 'cancelled'
  payment_status TEXT DEFAULT 'unpaid', -- 'unpaid', 'partial', 'paid', 'refunded'
  
  -- Delivery
  delivery_address TEXT,
  delivery_method TEXT, -- 'pickup', 'delivery', 'shipping'
  delivery_date DATE,
  return_date DATE,
  
  -- Notes
  special_requirements TEXT,
  internal_notes TEXT,
  
  -- Tracking
  assigned_staff TEXT,
  confirmation_number TEXT UNIQUE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_bookings_robot_id ON public.rental_bookings(robot_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON public.rental_bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_payment_status ON public.rental_bookings(payment_status);
CREATE INDEX IF NOT EXISTS idx_bookings_dates ON public.rental_bookings(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_bookings_customer_email ON public.rental_bookings(customer_email);

-- Function to update 'updated_at' timestamp
CREATE OR REPLACE FUNCTION update_bookings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for auto-updating updated_at
DROP TRIGGER IF EXISTS trigger_update_bookings_updated_at ON public.rental_bookings;
CREATE TRIGGER trigger_update_bookings_updated_at
    BEFORE UPDATE ON public.rental_bookings
    FOR EACH ROW
    EXECUTE FUNCTION update_bookings_updated_at();

-- Function to generate confirmation number
CREATE OR REPLACE FUNCTION generate_confirmation_number()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.confirmation_number IS NULL THEN
        NEW.confirmation_number := 'RB-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-' || LPAD(NEW.id::TEXT, 6, '0');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for auto-generating confirmation number
DROP TRIGGER IF EXISTS trigger_generate_confirmation_number ON public.rental_bookings;
CREATE TRIGGER trigger_generate_confirmation_number
    BEFORE INSERT ON public.rental_bookings
    FOR EACH ROW
    EXECUTE FUNCTION generate_confirmation_number();

-- Enable Row Level Security (for Supabase)
ALTER TABLE public.rental_bookings ENABLE ROW LEVEL SECURITY;

-- Customers can view their own bookings
CREATE POLICY "Allow customers to view own bookings" ON public.rental_bookings
  FOR SELECT USING (customer_email = auth.jwt() ->> 'email');

-- Admins can view all bookings
CREATE POLICY "Allow admin read access on bookings" ON public.rental_bookings
  FOR SELECT USING (auth.role() = 'authenticated');

-- Admins can modify bookings
CREATE POLICY "Allow admin write access on bookings" ON public.rental_bookings
  FOR ALL USING (auth.role() = 'authenticated');
