-- =====================================================
-- AUDIT LOG TABLE SCHEMA (OPTIONAL - SECURITY)
-- Tracks all important system events and changes
-- =====================================================

CREATE TABLE IF NOT EXISTS public.audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Event Details
  event_type TEXT NOT NULL, -- 'robot_created', 'robot_updated', 'robot_deleted', 'admin_login', 'booking_created', etc.
  table_name TEXT,
  record_id BIGINT,
  
  -- User Information
  admin_id BIGINT REFERENCES public.admins(id),
  admin_email TEXT,
  
  -- Changes (stored as JSON)
  old_values JSONB,
  new_values JSONB,
  
  -- Context
  ip_address TEXT,
  user_agent TEXT,
  
  -- Additional metadata
  description TEXT
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_audit_log_event_type ON public.audit_log(event_type);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON public.audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_admin_id ON public.audit_log(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_table_record ON public.audit_log(table_name, record_id);

-- Enable Row Level Security (for Supabase)
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

-- Only super_admins can view audit logs
CREATE POLICY "Allow super_admin read access on audit_log" ON public.audit_log
  FOR SELECT USING (auth.jwt() ->> 'role' = 'super_admin');

-- System can insert audit logs
CREATE POLICY "Allow system insert on audit_log" ON public.audit_log
  FOR INSERT WITH CHECK (true);
