-- =====================================================
-- CMS (Content Management System) Schema
-- Enables dynamic management of all website content
-- =====================================================

-- =====================================================
-- 1. PAGES TABLE
-- Stores main page information for all website sections
-- =====================================================
CREATE TABLE IF NOT EXISTS public.pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Page Identity
  slug TEXT UNIQUE NOT NULL, -- URL slug (e.g., 'inspection', 'manufacturing')
  title TEXT NOT NULL,
  subtitle TEXT,
  
  -- Hero Section
  hero_image TEXT, -- URL to hero image
  content TEXT, -- Main page description/content
  
  -- Categorization
  category TEXT NOT NULL, -- 'products', 'solutions', 'industries', 'company', 'resources'
  
  -- Display Settings
  is_published BOOLEAN DEFAULT TRUE,
  display_order INTEGER DEFAULT 0,
  
  -- SEO
  meta_description TEXT,
  meta_keywords TEXT[]
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_pages_slug ON public.pages(slug);
CREATE INDEX IF NOT EXISTS idx_pages_category ON public.pages(category);
CREATE INDEX IF NOT EXISTS idx_pages_published ON public.pages(is_published);

-- =====================================================
-- 2. PAGE_SECTIONS TABLE
-- Content blocks/sections within pages
-- =====================================================
CREATE TABLE IF NOT EXISTS public.page_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Reference
  page_id BIGINT REFERENCES public.pages(id) ON DELETE CASCADE,
  
  -- Section Details
  section_type TEXT NOT NULL, -- 'features', 'benefits', 'text', 'cta', 'custom'
  title TEXT,
  content TEXT,
  
  -- Flexible Data Storage
  data JSONB, -- Store array of items, features, etc.
  
  -- Display
  display_order INTEGER DEFAULT 0
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_sections_page_id ON public.page_sections(page_id);
CREATE INDEX IF NOT EXISTS idx_sections_order ON public.page_sections(page_id, display_order);

-- =====================================================
-- 3. PAGE_ITEMS TABLE
-- Individual items/cards displayed on pages
-- =====================================================
CREATE TABLE IF NOT EXISTS public.page_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Reference
  page_id BIGINT REFERENCES public.pages(id) ON DELETE CASCADE,
  
  -- Item Details
  name TEXT NOT NULL,
  image_url TEXT,
  description TEXT,
  
  -- Specifications (stored as JSON array)
  specs JSONB, -- ["Spec 1", "Spec 2", "Spec 3"]
  
  -- Call to Action
  cta_text TEXT, -- e.g., "VIEW SPECS", "INQUIRE"
  cta_link TEXT,
  
  -- Display
  display_order INTEGER DEFAULT 0
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_items_page_id ON public.page_items(page_id);
CREATE INDEX IF NOT EXISTS idx_items_order ON public.page_items(page_id, display_order);

-- =====================================================
-- 4. NAVIGATION_MENU TABLE
-- Dynamic navigation structure
-- =====================================================
CREATE TABLE IF NOT EXISTS public.navigation_menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Hierarchy
  parent_id BIGINT REFERENCES public.navigation_menu(id) ON DELETE CASCADE,
  
  -- Menu Item Details
  label TEXT NOT NULL, -- Display text
  slug TEXT, -- URL slug (if links to a page)
  url TEXT, -- Full URL (if external link)
  
  -- Categorization
  category TEXT, -- 'products', 'solutions', 'industries', 'company', 'resources'
  
  -- Display Settings
  display_order INTEGER DEFAULT 0,
  is_visible BOOLEAN DEFAULT TRUE,
  
  -- Icon/Image (optional)
  icon TEXT
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_nav_parent ON public.navigation_menu(parent_id);
CREATE INDEX IF NOT EXISTS idx_nav_category ON public.navigation_menu(category);
CREATE INDEX IF NOT EXISTS idx_nav_visible ON public.navigation_menu(is_visible);
CREATE INDEX IF NOT EXISTS idx_nav_order ON public.navigation_menu(category, display_order);

-- =====================================================
-- TRIGGERS FOR AUTO-UPDATING TIMESTAMPS
-- =====================================================

-- Pages trigger
CREATE OR REPLACE FUNCTION update_pages_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_pages_updated_at ON public.pages;
CREATE TRIGGER trigger_update_pages_updated_at
    BEFORE UPDATE ON public.pages
    FOR EACH ROW
    EXECUTE FUNCTION update_pages_updated_at();

-- Sections trigger
CREATE OR REPLACE FUNCTION update_sections_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_sections_updated_at ON public.page_sections;
CREATE TRIGGER trigger_update_sections_updated_at
    BEFORE UPDATE ON public.page_sections
    FOR EACH ROW
    EXECUTE FUNCTION update_sections_updated_at();

-- Items trigger
CREATE OR REPLACE FUNCTION update_items_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_items_updated_at ON public.page_items;
CREATE TRIGGER trigger_update_items_updated_at
    BEFORE UPDATE ON public.page_items
    FOR EACH ROW
    EXECUTE FUNCTION update_items_updated_at();

-- Navigation trigger
CREATE OR REPLACE FUNCTION update_nav_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_nav_updated_at ON public.navigation_menu;
CREATE TRIGGER trigger_update_nav_updated_at
    BEFORE UPDATE ON public.navigation_menu
    FOR EACH ROW
    EXECUTE FUNCTION update_nav_updated_at();

-- =====================================================
-- ROW LEVEL SECURITY (for Supabase)
-- =====================================================

ALTER TABLE public.pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.navigation_menu ENABLE ROW LEVEL SECURITY;

-- Public read access for published pages
CREATE POLICY "Allow public read on published pages" ON public.pages
  FOR SELECT USING (is_published = TRUE);

-- Admin full access
CREATE POLICY "Allow admin full access on pages" ON public.pages
  FOR ALL USING (auth.role() = 'authenticated');

-- Public read for sections (if parent page is published)
CREATE POLICY "Allow public read on sections" ON public.page_sections
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.pages 
      WHERE pages.id = page_sections.page_id 
      AND pages.is_published = TRUE
    )
  );

CREATE POLICY "Allow admin full access on sections" ON public.page_sections
  FOR ALL USING (auth.role() = 'authenticated');

-- Public read for items (if parent page is published)
CREATE POLICY "Allow public read on items" ON public.page_items
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.pages 
      WHERE pages.id = page_items.page_id 
      AND pages.is_published = TRUE
    )
  );

CREATE POLICY "Allow admin full access on items" ON public.page_items
  FOR ALL USING (auth.role() = 'authenticated');

-- Public read for visible navigation
CREATE POLICY "Allow public read on visible navigation" ON public.navigation_menu
  FOR SELECT USING (is_visible = TRUE);

CREATE POLICY "Allow admin full access on navigation" ON public.navigation_menu
  FOR ALL USING (auth.role() = 'authenticated');

-- =====================================================
-- SAMPLE DATA - Migration from hardcoded content
-- =====================================================

-- Insert sample pages (Products - Solutions)
INSERT INTO public.pages (slug, title, subtitle, hero_image, content, category, display_order) VALUES
-- Solutions
('inspection', 'Inspection & Monitoring', 'Automated sensing for asset health.', 
 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80',
 'The Robot carries thermal cameras, acoustic imagers, and lidars to perform routine inspections autonomously, detecting anomalies before they become failures.',
 'solutions', 1),

('safety-response', 'Safety & Emergency Response', 'Keep people out of harm''s way.',
 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=80',
 'Deploy robots to dangerous environments like chemical spills, fires, or radiation zones to assess the situation while keeping human responders at a safe distance.',
 'solutions', 2),

('research', 'Research & Innovation', 'Pushing the boundaries of what is possible.',
 'https://images.unsplash.com/photo-1531746790731-6c087fecd05a?auto=format&fit=crop&w=1200&q=80',
 'Our platforms are the gold standard for robotics research. From universities to corporate R&D labs, The Robot and Advanced Humanoid are helping invent the future.',
 'solutions', 3),

-- Industries
('manufacturing', 'Manufacturing Automation', 'Optimization and reliability for the factory floor.',
 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80',
 'Our robots navigate unstructured environments to automate inspection, remote operation, and material handling tasks, keeping your team safe and your operations running smoothly.',
 'industries', 1),

('logistics', 'Warehouse & Logistics', 'Streamlined box moving and case handling.',
 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaad5b?auto=format&fit=crop&w=1200&q=80',
 'Automate the dull, dirty, and dangerous tasks in your warehouse. Logistics Robot handles cases up to 50lbs, improving throughput and reducing injury risks.',
 'industries', 2)

ON CONFLICT (slug) DO NOTHING;

-- Insert sample sections for inspection page
INSERT INTO public.page_sections (page_id, section_type, title, data, display_order)
SELECT 
  p.id,
  'features',
  'Inspection Utility',
  '[
    {"title": "Predictive Maintenance", "desc": "Catch overheating components before they cause a shutdown."},
    {"title": "Site Digitization", "desc": "Regularly capture 3D data to maintain a current digital twin."},
    {"title": "Remote Access", "desc": "Access hard-to-reach or dangerous areas without human exposure."}
  ]'::jsonb,
  1
FROM public.pages p
WHERE p.slug = 'inspection'
ON CONFLICT DO NOTHING;

-- Insert sample items for inspection page
INSERT INTO public.page_items (page_id, name, image_url, specs, cta_text, display_order)
SELECT 
  p.id,
  'The Robot CAM+IR',
  'https://images.unsplash.com/photo-1563968743333-044cef800494?auto=format&fit=crop&w=400&q=80',
  '["Thermal 30Hz", "30x Optical Zoom", "Built-in Speaker"]'::jsonb,
  'VIEW SPECS',
  1
FROM public.pages p
WHERE p.slug = 'inspection'
ON CONFLICT DO NOTHING;

-- Insert sample navigation menu
INSERT INTO public.navigation_menu (label, category, display_order, is_visible) VALUES
('PRODUCTS', 'products', 1, true),
('SOLUTIONS', 'solutions', 2, true),
('INDUSTRIES', 'industries', 3, true),
('COMPANY', 'company', 4, true),
('RESOURCES', 'resources', 5, true)
ON CONFLICT DO NOTHING;
