-- =====================================================
-- ROBOT BEING - Complete Database Schema
-- =====================================================

-- =====================================================
-- 1. ROBOTS TABLE
-- Stores all robot products with categorization
-- =====================================================
CREATE TABLE IF NOT EXISTS public.robots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Basic Information
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  
  -- Categorization
  type TEXT NOT NULL, -- Main category: 'Humanoid Robots', 'Drones', 'Security Gadgets', 'Essential AI Gadgets and Smart Homes'
  sub_category TEXT DEFAULT 'General', -- Usage: 'Rental', 'Education', 'Expos', 'Events', 'Agriculture', 'Security', 'General'
  
  -- Media
  image_url TEXT,
  
  -- Technical Specifications (Optional - can be NULL)
  height TEXT, -- e.g., '110 cm'
  weight TEXT, -- e.g., '30 kg'
  battery_life TEXT, -- e.g., '90 mins'
  speed TEXT, -- e.g., '1.6 m/s'
  payload_capacity TEXT, -- e.g., '23 kg'
  
  -- Pricing (Optional)
  rental_price_daily DECIMAL(10, 2),
  rental_price_weekly DECIMAL(10, 2),
  rental_price_monthly DECIMAL(10, 2),
  purchase_price DECIMAL(10, 2),
  
  -- Availability
  is_available BOOLEAN DEFAULT TRUE,
  stock_quantity INTEGER DEFAULT 1,
  
  -- Additional Details
  datasheet_url TEXT,
  video_url TEXT,
  features JSONB, -- Store array of features as JSON
  
  -- Metadata
  tags TEXT[], -- Array of searchable tags
  manufacturer TEXT,
  model_number TEXT,
  year_released INTEGER
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_robots_type ON public.robots(type);
CREATE INDEX IF NOT EXISTS idx_robots_sub_category ON public.robots(sub_category);
CREATE INDEX IF NOT EXISTS idx_robots_is_available ON public.robots(is_available);
CREATE INDEX IF NOT EXISTS idx_robots_tags ON public.robots USING GIN(tags);

-- =====================================================
-- 2. CONTACTS TABLE
-- Stores contact form submissions
-- =====================================================
CREATE TABLE IF NOT EXISTS public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Contact Information
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  
  -- Organization
  company TEXT NOT NULL,
  industry TEXT NOT NULL,
  
  -- Message
  message TEXT NOT NULL,
  
  -- Status tracking
  status TEXT DEFAULT 'new', -- 'new', 'contacted', 'qualified', 'closed'
  assigned_to TEXT,
  notes TEXT,
  
  -- Metadata
  source TEXT DEFAULT 'website', -- 'website', 'phone', 'email', 'event'
  ip_address TEXT,
  user_agent TEXT
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_contacts_email ON public.contacts(email);
CREATE INDEX IF NOT EXISTS idx_contacts_status ON public.contacts(status);
CREATE INDEX IF NOT EXISTS idx_contacts_created_at ON public.contacts(created_at DESC);

-- =====================================================
-- 3. ADMINS TABLE
-- Stores admin user credentials
-- =====================================================
CREATE TABLE IF NOT EXISTS public.admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Authentication
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL, -- Hashed with bcrypt
  
  -- Profile
  full_name TEXT,
  role TEXT DEFAULT 'admin', -- 'admin', 'super_admin', 'viewer'
  
  -- Status
  is_active BOOLEAN DEFAULT TRUE,
  last_login TIMESTAMPTZ,
  
  -- Security
  failed_login_attempts INTEGER DEFAULT 0,
  locked_until TIMESTAMPTZ
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_admins_email ON public.admins(email);
CREATE INDEX IF NOT EXISTS idx_admins_is_active ON public.admins(is_active);

-- =====================================================
-- 4. RENTAL_BOOKINGS TABLE (Optional - for future use)
-- Stores rental booking information
-- =====================================================
CREATE TABLE IF NOT EXISTS public.rental_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Robot Reference
  robot_id BIGINT REFERENCES public.robots(id) ON DELETE CASCADE,
  
  -- Customer Information
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_company TEXT,
  
  -- Booking Details
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  duration_days INTEGER NOT NULL,
  
  -- Pricing
  total_price DECIMAL(10, 2) NOT NULL,
  deposit_amount DECIMAL(10, 2),
  
  -- Status
  status TEXT DEFAULT 'pending', -- 'pending', 'confirmed', 'active', 'completed', 'cancelled'
  payment_status TEXT DEFAULT 'unpaid', -- 'unpaid', 'partial', 'paid', 'refunded'
  
  -- Delivery
  delivery_address TEXT,
  delivery_method TEXT, -- 'pickup', 'delivery', 'shipping'
  
  -- Notes
  special_requirements TEXT,
  internal_notes TEXT
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_bookings_robot_id ON public.rental_bookings(robot_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON public.rental_bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_dates ON public.rental_bookings(start_date, end_date);

-- =====================================================
-- 5. AUDIT_LOG TABLE (Optional - for tracking changes)
-- Stores all important system events
-- =====================================================
CREATE TABLE IF NOT EXISTS public.audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Event Details
  event_type TEXT NOT NULL, -- 'robot_created', 'robot_updated', 'robot_deleted', 'admin_login', etc.
  table_name TEXT,
  record_id BIGINT,
  
  -- User Information
  admin_id BIGINT REFERENCES public.admins(id),
  admin_email TEXT,
  
  -- Changes
  old_values JSONB,
  new_values JSONB,
  
  -- Context
  ip_address TEXT,
  user_agent TEXT
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_audit_log_event_type ON public.audit_log(event_type);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON public.audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_admin_id ON public.audit_log(admin_id);

-- =====================================================
-- SAMPLE DATA INSERTS
-- =====================================================

-- Insert sample robots with sub-categories
INSERT INTO public.robots (name, type, sub_category, description, image_url, height, weight, battery_life, speed) 
VALUES 
  ('Humanoid Alpha', 'Humanoid Robots', 'Rental', 'Advanced bipedal robot for multi-purpose applications', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', '110 cm', '30 kg', '90 mins', '1.6 m/s'),
  ('Humanoid Beta', 'Humanoid Robots', 'Education', 'Educational humanoid robot for STEM programs', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', '105 cm', '28 kg', '120 mins', '1.4 m/s'),
  ('Drone X-1', 'Drones', 'Agriculture', 'High-performance aerial vehicle for crop monitoring', 'https://images.unsplash.com/photo-1506947411487-a56738267384?auto=format&fit=crop&w=800&q=80', NULL, '2.5 kg', '45 mins', '15 m/s'),
  ('SmartEye Cam', 'Security Gadgets', 'Security', 'AI-powered security camera with real-time threat detection', 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80', '15 cm', '0.5 kg', 'AC Powered', NULL),
  ('Butler AI', 'Essential AI Gadgets and Smart Homes', 'General', 'Integrated AI solution for smart home automation', 'https://images.unsplash.com/photo-1558002038-1091a1661116?auto=format&fit=crop&w=800&q=80', '30 cm', '1.2 kg', 'AC Powered', NULL)
ON CONFLICT DO NOTHING;

-- Insert default admin (password: MailBala&*^001)
INSERT INTO public.admins (email, password, full_name, role) 
VALUES ('robotbeings@gmail.com', '$2b$10$kWbaQhpY1MtndXuICGB5Zuw..wBCMtSc233fs4QS0kM8netYyBPL6', 'Admin User', 'super_admin')
ON CONFLICT (email) DO NOTHING;

-- =====================================================
-- FUNCTIONS AND TRIGGERS
-- =====================================================

-- Function to update 'updated_at' timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for robots table
DROP TRIGGER IF EXISTS update_robots_updated_at ON public.robots;
CREATE TRIGGER update_robots_updated_at
    BEFORE UPDATE ON public.robots
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger for admins table
DROP TRIGGER IF EXISTS update_admins_updated_at ON public.admins;
CREATE TRIGGER update_admins_updated_at
    BEFORE UPDATE ON public.admins
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger for rental_bookings table
DROP TRIGGER IF EXISTS update_bookings_updated_at ON public.rental_bookings;
CREATE TRIGGER update_bookings_updated_at
    BEFORE UPDATE ON public.rental_bookings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- VIEWS (Optional - for easier querying)
-- =====================================================

-- View for available robots
CREATE OR REPLACE VIEW public.available_robots AS
SELECT 
  id,
  name,
  type,
  sub_category,
  description,
  image_url,
  rental_price_daily,
  rental_price_weekly,
  rental_price_monthly,
  stock_quantity
FROM public.robots
WHERE is_available = TRUE AND stock_quantity > 0;

-- View for robots by category
CREATE OR REPLACE VIEW public.robots_by_category AS
SELECT 
  type as category,
  sub_category,
  COUNT(*) as robot_count,
  AVG(rental_price_daily) as avg_daily_price
FROM public.robots
WHERE is_available = TRUE
GROUP BY type, sub_category
ORDER BY type, sub_category;

-- =====================================================
-- PERMISSIONS (Adjust based on your Supabase setup)
-- =====================================================

-- Enable Row Level Security
ALTER TABLE public.robots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rental_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

-- Public read access for robots
CREATE POLICY "Allow public read access on robots" ON public.robots
  FOR SELECT USING (true);

-- Admin-only write access for robots
CREATE POLICY "Allow admin write access on robots" ON public.robots
  FOR ALL USING (auth.role() = 'authenticated');

-- Public insert for contacts
CREATE POLICY "Allow public insert on contacts" ON public.contacts
  FOR INSERT WITH CHECK (true);

-- Admin read access for contacts
CREATE POLICY "Allow admin read access on contacts" ON public.contacts
  FOR SELECT USING (auth.role() = 'authenticated');
