-- Create the contacts table if it doesn't exist
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  first_name text not null,
  last_name text not null,
  email text not null,
  company text not null,
  industry text not null,
  message text not null
);
