-- Create the robots table if it doesn't exist
create table if not exists public.robots (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  name text not null,
  type text not null,
  description text not null,
  image_url text,
  sub_category text default 'General'
);

-- Insert initial sample data (using individual statements for better compatibility)
insert into public.robots (name, type, description, image_url) values ('Humanoid Robots', 'Humanoid', 'Advanced bipedal robots for multi-purpose applications', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80');
insert into public.robots (name, type, description, image_url) values ('Drones', 'Aerial', 'High-performance aerial vehicles for surveillance and inspection', 'https://images.unsplash.com/photo-1506947411487-a56738267384?auto=format&fit=crop&w=800&q=80');
insert into public.robots (name, type, description, image_url) values ('Security Gadgets', 'Security', 'Smart security solutions for home and enterprise', 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80');
insert into public.robots (name, type, description, image_url) values ('Essential AI Gadgets and Smart Homes', 'Smart Home', 'Integrated AI solutions for a smarter living environment', 'https://images.unsplash.com/photo-1558002038-1091a1661116?auto=format&fit=crop&w=800&q=80');

-- Create the contacts table if it doesn't exist
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  first_name text not null,
  last_name text not null,
  email text not null,
  company text not null,
  industry text not null,
  message text not null
);

-- Create the admins table if it doesn't exist
create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  email text unique not null,
  password text not null
);

-- Note: In a real app, passwords should be hashed.
-- This is just for demonstration if inserted via SQL.
-- default: robotbeings@gmail.com / MailBala&*^001 (hashed)
insert into public.admins (email, password) values ('robotbeings@gmail.com', '$2b$10$kWbaQhpY1MtndXuICGB5Zuw..wBCMtSc233fs4QS0kM8netYyBPL6');
